### ISSUE TITLE
how may i reduce the time of appear of the first image?

### ISSUE THREAD

**Issue by gellina** [jaysalvat/vegas#101]
hi,
is there a way to reduce the time in witch the first image is shown?

i thought that was here:

"
var defaults = {
        slide:              0,
        delay:             5000,
        preload:            false,
        preloadImage:       false,
        preloadVideo:       false,
        timer:              true,
        overlay:            false,
        autoplay:           true,
        shuffle:            false,
        cover:              true,
        color:              null,
        align:              'center',
        valign:             'center',
        transition:         'fade',
        transitionDuration: 100,
        transitionRegister: [],
        animation:          null,
        animationDuration:  'auto',
        animationRegister:  [],

"

the "delay" from 5000 to 100 ...for example...
but it doesn't change.

thanks for help

**Comment by jaysalvat** [comment]
Hello,
first image is shown when it is fully loaded.
No way to reduce time. Sorry :)
