### ISSUE TITLE
There's a way to insert a link to an specific background "slide"?

### ISSUE THREAD

**Issue by vedovato** [jaysalvat/vegas#102]
I'm trying with jquery with walk method on index 0 but it isn't working. Can you say if it is possible? Thank you :)

**Comment by jaysalvat** [comment]
Hello,

Yes you can.
Vegas is for backgrounds slideshows, Backgrounds usually don't have link. So add any HTML code in your vegas container.Display/hide/change your HTML element in the vegas `walk`method.

**Comment by vedovato** [comment]
Thanks!

**Comment by vedovato** [comment]
Hey, can you help me set the link only on first background item? I'm trying this but i can only identify the first "slide" but can't set a link to it. What i'm doing wrong? I'm simulatng "click" printing a console.log instead of redirecting and is a way to check the proper click at the right element.

```
$('#estanciaHomeSlider, body').vegas({
      slides: [
        { src: directory_uri.stylesheet_directory_uri + '/assets/images/bg1.png' },
        { src: directory_uri.stylesheet_directory_uri + '/assets/images/bg2.png' },
        { src: directory_uri.stylesheet_directory_uri + '/assets/images/bg3.png' }
      ],
      transition: 'fade',
      walk: function(slide, setting){
        if(slide == 0) {
          var x = this.context.childNodes[0].childNodes[0]
          $(x).click(function(){
            console.warn('clicked!')
          })
        }
      }
    })
 })
```

**Comment by jaysalvat** [comment]
Hello :)

Something like that should be working...
I would need to investigate and make some tests on your code.
If you need me to work on your code, please contact me privately by support section on http://vegas.jaysalvat.com

I close, this is not a Vegas issue.

Regards.
