### ISSUE TITLE
Override delay for one slide

### ISSUE THREAD

**Issue by kamilchm** [jaysalvat/vegas#103]
Hi,

is there a way to set ``delay`` i global vegas settings and then override it for particular slide in its own settings?
I tried to do it for video slide and it looks like it doesn't work :(

**Comment by jaysalvat** [comment]
Hello.

Yes you can:
http://vegas.jaysalvat.com/documentation/settings/

I've just tried and it work perfectly even for video.

:)

**Comment by kamilchm** [comment]
Sorry, my bad. I put the delay to deep, inside video element.
Everything works like you described :+1: 
Thx for your wokr on vegas! Good piece of software.
