### ISSUE TITLE
Delaying start of auto slideshow

### ISSUE THREAD

**Issue by dsiglin** [jaysalvat/vegas#104]
First thank you for this simple and great slideshow.

Here's my dilemma. The div that has vegas applied to it has an initial background-image. Is it possible to delay the initialization of vegas by x amount of milliseconds? I'd like to show that image for say 15000 milliseconds and then kick into the random slideshow. Thanks in advance.

**Comment by jaysalvat** [comment]
Hello,

This is no built-in way to delay the initialization. 
Try to init Vegas in a setTimeout function.

:)

**Comment by dsiglin** [comment]
Alright, I did it and it's working now. Thanks, was just curious if there was an option I was missing.

**Comment by jaysalvat** [comment]
Great!

**Comment by dsiglin** [comment]
Hey @jaysalvat - one other question, When I resize my site vertically the image doesn't resize as well leaving a gap between the bottom of the image and the bottom of the browser. Is that expected?

**Comment by jaysalvat** [comment]
Hello,

Don't see it.
Do you see this issue on http://vegas.jaysalvat.com ?

**Comment by dsiglin** [comment]
No it doesn't happen there so the problem must be related to the interaction of fullpage.js and vegas. Ok thanks.
