### ISSUE TITLE
Shuffle not working

### ISSUE THREAD

**Issue by rroblik** [jaysalvat/vegas#106]
Hi,

I saw in the demo that the ```shuffle``` feature was not working. (http://vegas.jaysalvat.com/documentation/methods/ , click on "play" then "shuffle" to test it)
I tried locally and... same result :(

Did I made something wrong or is it a (old) know bug ?

EDIT : 
I think manually shuffle the vegas "internal" ```slides``` array is not a good idea (as https://github.com/jaysalvat/vegas/issues/38) because I need sometimes to shuffle images, but sometimes not, to see new images (ajax loaded) in normal order (based on loaded time)

Thanks. Regards

**Comment by jaysalvat** [comment]
Hello and thanks for the bug report. I will check it in a few days.

Thanks again.

**Comment by jaysalvat** [comment]
Hello @rroblik.

I just tried and it works properly to me.

Method ```$elmt.vegas('shuffle');``` or ```{ shuffle: true }``` in the vegas settings.

The link you gave in your edit is for Vegas v1.

**Comment by soee** [comment]
Shuffle option also works for me :) I;m using 2.x version.
