### ISSUE TITLE
Animation is snatchy and shaky in Mozilla Firefox

### ISSUE THREAD

**Issue by JadaVonRuth** [jaysalvat/vegas#107]
When using **animation**, all browsers except mozilla(latest) are working fine. In Mozilla is hard to watch(even examples in documentation are doing that). Does not matter which animation I choose, it always shakes and snatches. Maybe it has to do with calculating movement, rounding. My goal was to achieve of slow motion approaching effect and whatever value I put into **animationDuration ** parameter it is always quite fast (tried 80000). It is pitty if this nice plugin could not be used with animation because of mozilla.

**Comment by jaysalvat** [comment]
Hello,

I don't see any problem on my Firefox 43 (Mac). 
You're the first one to report this issue.

Can you test another Firefox on another computer ?

**Comment by JadaVonRuth** [comment]
Hello,

I tested on another 2 computers (both win7), one of them has the same problem, the second one was drawing correctly. Weird.

**Comment by jaysalvat** [comment]
So it's on specific Firefox versions.
Animation just use CSS animation. This is not a Vegas bug but a poor Firefox implementation I guess.
Can't do much on this sorry.

**Comment by JadaVonRuth** [comment]
I figured it out in vegas.css based on article on the web I changed this CSS rule

```
@keyframes kenburns
{
    0%
    {
        -moz-transform: scale(1.5) rotate(0.1deg);
        -ms-transform: scale(1.5) rotate(0.1deg);
        -o-transform: scale(1.5) rotate(0.1deg);
        -webkit-transform: scale(1.5) rotate(0.1deg);
        transform: scale(1.5) rotate(0.1deg);
    }

    100%
    {
        -moz-transform: scale(1);
        -ms-transform: scale(1);
        -o-transform: scale(1);
        -webkit-transform: scale(1);
        transform: scale(1);
    }
}
```

where rotate(0.1deg); somehow fixes the problem for firefox and explorer and makes it smoother.

**Comment by jaysalvat** [comment]
Thanks for the tip! I will try it.
