### ISSUE TITLE
first image transition issue

### ISSUE THREAD

**Issue by robsource** [jaysalvat/vegas#108]
I want to use the slideLeft2 transition but having an issue when the page first loads.  When using the slideLeft2 transition the page loads with an empty div and then the first image slides in.  It looks strange.  I applied a different transition to the first slide "fade" which avoids this until the slideshow repeats and then it fades that particular slide instead of sliding it like the others.  Not sure if that makes sense.  Basically, I want the page to load with the first image in place rather than sliding in but I want to use the slide effect on all slides including the first one thereafter.  Is there a way to do this?  Thanks so much and awesome work btw.

$("#home").vegas({
    slides: [
        { src: "images/grph_home5.jpg", transition: 'fade' },
        { src: "images/grph_home6.jpg" },
        { src: "images/grph_home7.jpg" }
    ],
	loading:true,
	timer: false,
	transition: 'slideLeft2',
	color: '#000000',
	delay: 4000,
	transitionDuration: 750
});

**Comment by jaysalvat** [comment]
Hello,

Please use methods 'walk' callback and 'options' method to change the transition after the first slide.
http://vegas.jaysalvat.com/documentation/settings/#callbacks-events
http://vegas.jaysalvat.com/documentation/methods/

**Comment by robsource** [comment]
Awesome.  Thanks pointing in the right direction.  For anyone else wondering how this would be done, it would look something like:
`$("#home").vegas({
    slides: [
        { src: "images/grph_1.jpg" },
        { src: "images/grph_2.jpg" },
        { src: "images/grph_3.jpg" }
    ],
	loading:true,
	timer: false,
	transition: 'fade',
	color: '#000000',
	delay: 4000,
	transitionDuration: 750,
	walk: function (index, slideSettings) {
        $("#home").vegas('options', 'transition', 'slideLeft2');
    }
});`

**Comment by jaysalvat** [comment]
Great!
Thanks for sharing.

**Comment by ryanjbonnell** [comment]
For readability, here's a beautified version of the code example:

```
$("#home").vegas({
  slides: [
    { src: "images/grph_1.jpg" },
    { src: "images/grph_2.jpg" },
    { src: "images/grph_3.jpg" }
  ],
  loading: true,
  timer: false,
  transition: 'fade',
  color: '#000000',
  delay: 4000,
  transitionDuration: 750,
  walk: function(index, slideSettings) {
    $("#home").vegas('options', 'transition', 'slideLeft2');
  }
});
```
