### ISSUE TITLE
Transition without stopping

### ISSUE THREAD

**Issue by DaveBeirne** [jaysalvat/vegas#109]
Hi, 

First off great plugin! 

This is not really an issue but if you have a slideshow with for e.g. **Ken Burns** and a **fade** transition between slides. i noticed once the full image is shown there is a slight pause and then it loads the fade into the next image. it kinda breaks up the flow of the slides. 

I was wondering if it was possible not to have this pause so the image loads and then fades to the next image without that pause

Thanks

**Comment by jaysalvat** [comment]
Hello and thanks.

I never noticed that. Did you try to increase the animationDuration?

**Comment by DaveBeirne** [comment]
Hi Jay,

Thanks for that, in order to get it to transition without stopping i made the animationDuration longer than the Delay. 

`delay: 6000,
animationDuration: 7000, `

Thanks again

**Comment by jaysalvat** [comment]
Great.
