### ISSUE TITLE
Vegas function is not loading images in Rails app

### ISSUE THREAD

**Issue by SaintClair33** [jaysalvat/vegas#110]
I am trying to get my background images to load using the vegas function in my js file. But it is not able to find the images in my rails asset pipeline for some reason. I've tried "../images/bg1.pg" as well but that did not work either.  How do I get this to show in my Rails app?

**Error shown in console**
    GET:  http://hostname/images/bg1.jpg not found 

**Vegas function in JS file:**

    // Image background
    $.vegas({ src: '/images/bg1.jpg'
    });

    $.vegas('overlay', {
        src:'/images/06.png'
    });

**Location of where my JS files are stored in my asset pipeline:**

    app/assets/javascripts

**Location of where my images are located:**

    app/assets/images

**Comment by jaysalvat** [comment]
Hello,

If your images are not found, it's more a server/images/rails problems than a Vegas problem.
I can't help you sorry.

Your Vegas script seems weird though. Vegas is V2 now.
http://vegas.jaysalvat.com

Hope it helps.
:)
