### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by MichaelRise** [jaysalvat/vegas#113]
Hey,

I have all plugins in plugins.js and I don't initialize vagas, but I have error.

vegas.min.js:684 - Uncaught TypeError: Cannot read property 'length' of undefined
(anonymous function)	@	vegas.min.js:684

I use vegas.min.ja and vegas.min.js.map

When I remove "sourceMappingURL" and `||window.Zepto` I have no errors.

Please help.

**Comment by jaysalvat** [comment]
Hello,

Check the order of the plugins in your plugins.js and check if jquery or zepto are included.

**Comment by MichaelRise** [comment]
My code:

```
		<!-- JS -->
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/plugins.js"></script>

		<script type="text/javascript" src="js/main.js"></script>

	</body>
</html>
```

I use jquery 1.12.3.
In plugins.js I have vegas.min.js at the bottom/end.

Sorry for my english.

**Comment by jaysalvat** [comment]
I don't understand.
Your error talks about 'vegas.min.js:684' and you told me vegas is a plugins.js file.

**Comment by MichaelRise** [comment]
I include all plugins in one file (easing, owlCarousel, flexslider, swiperslider, vegas etc.) - plugins.js
I have error in vegas.min.js because I use "sourceMappingURL".
`//# sourceMappingURL=vegas.min.js.map`
Can I remove "sourceMappingURL".?

Thanks for help.

**Comment by MichaelRise** [comment]
Sorry, this error is in the "swiperSlider" and I fixed this.
Thsnkf for your help.

Best Regards
Michael

**Comment by jaysalvat** [comment]
Great:(
