### ISSUE TITLE
White background with no image on Chrome + Windows

### ISSUE THREAD

**Issue by costaprofunda** [jaysalvat/vegas#115]
Hi,
today I met the following problem:
there were no images, white background only for Chrome Windows remote server. Not every time, but in about 50% of reloading cases. Works for localhost, Chrome Mac and Firefox (Mac, Win). 
In fact the image was loaded but the opacity was 0. The plugin was initiated, play process started, but no 'walk' triggered. After debugging vegas.js I found that the problem was in str. 509:
`img.onload = go;`.
I googled about weird behavior of onload method, and the decision to replace this string with:
`go();`
solved my problem.
Maybe there is a more elegant way to fix it.

**Comment by jaysalvat** [comment]
Hello,
Never had any complaint about this
Does this issue occurs on vegas website or just on yours?

Watch out, replacing ìmg.onload = go;` by `go()` launch the slideshow even if the image is not loaded. This is not the expected behavior.

**Comment by costaprofunda** [comment]
Hi,
the issue occurs on my website. I've deployed the [version](http://dev.team2own.com/splash) with initial code (img.onload = go). Check with Windows Chrome.

**Comment by Miguel-gh96** [comment]
I had same error and I have solved the same way. ( img.onload = go() )

**Comment by jaysalvat** [comment]
Thanks @costaprofunda  but sorry, I have no window and it works perfectly on Chrome for Mac.

Please try to invert these lines.

    img.onload = go;
    img.src = src;

**Comment by costaprofunda** [comment]
Tried: didn't solve the problem unfortunately.

**Comment by costaprofunda** [comment]
Ok, seems I found the solution with onload. 
According to latest comment [here](http://stackoverflow.com/questions/5820209/image-onload-event-not-working-in-chrome) I've initialized img variable at str. 346.
`img           = new Image();`
and have removed img init at str. 431.
Everything works.
