### ISSUE TITLE
Slide background color

### ISSUE THREAD

**Issue by jrean** [jaysalvat/vegas#116]
Hi,

The documentation mentions we can use the `color` option to define the slide background color.
> color	-	Slide background color.

I tried many values `000000`, `#000000`, `white`, ... but it doesn't work.
What am I missing?

Thank you

**Comment by jaysalvat** [comment]
Hello,

Just tried, it works.

Setting ```{ color: 'red' }``` adds ```background-color: red``` to the slide.

```
<div class="vegas-slide-inner vegas-animation-kenburnsRight" style="animation-duration: 20000ms; background-image: url(image.jpg); background-color: red; background-size: cover; background-position: 50% 50%;"></div>
```

**Comment by jrean** [comment]
Hi Jay,
Thank you for the quick reply.
The value must be only the color by name? Right?
Maybe you can add a quick update to the excellent documentation on your website so it is cristal clear of the type of value allowed?

Thank you very much for your great work!

**Comment by jaysalvat** [comment]
No @jrean :)

it sets the ```background-color``` property, so any color (hexa or name) values are allowed.
