### ISSUE TITLE
Walk is never called when there are less than 2 slides

### ISSUE THREAD

**Issue by kamilchm** [jaysalvat/vegas#118]
I use ``walk`` to load new slides when displaying last one from current slideshow so I can update slideshows live. But when there are one or zero slides vegas stops to call ``walk``.
Any clues how can I fix this?

**Comment by jaysalvat** [comment]
Hello,

Just checked, ``walk`` is called when the slideshow is started. If there is only 1 slide, there is no slide rotation. Just 1 fixed background.
0 slide slideshow is not an option :)
