### ISSUE TITLE
[REQUEST] Add SASS file

### ISSUE THREAD

**Issue by soee** [jaysalvat/vegas#120]
Hi, it would be very useful to have SASS file with styles available. This way we can import it to our projects easily, modify, compile and merge with other files :)

**Comment by jaysalvat** [comment]
Hello Soee,

No need of SASS for such a simple CSS file. 
Note, you can import regular CSS file with SASS.

```sass
@import "/js/vegas/vegas.css"
```

This CSS file is not meat to be modified. Except for the Timer bar color, there is no need of vars.
If you need to, just overwrite the color somewhere in one of you SASS files.

```sass
.vegas-timer-progress
    background: white
```

**Comment by soee** [comment]
Sure but for example configurable scale or translate values in keyframe through variable would be cool :)

**Comment by jaysalvat** [comment]
That makes sens.

Here it is :)
https://github.com/jaysalvat/vegas/tree/master/src

**Comment by soee** [comment]
Thnk you very much. I'll test that later tonight :)
