### ISSUE TITLE
[REQUEST/QUESTION] Slideshow thumbnails

### ISSUE THREAD

**Issue by soee** [jaysalvat/vegas#121]
The main purpose of this plugin is to make it easy to render background slideshow and it does it perfect :)

One more feature i would like to see here out-of-the-box is the navigation using thumbnails. I'm sure it can be achieved using current callbacks/options plugin provides but maybe sningle setting like "showThumbnails" would be even better.

Someone may ask why do i need thumbnails for background slideshow :) Well this was a client request recently and such option would make managing slider in the Neos CMS backend (i'm working on a plugin for it) much easier.

**Comment by jaysalvat** [comment]
Thanks for the request.
You summarize the situation well. It's a background (not foreground) plugin and it can be easily done with callbacks and methods. :)

I can't and don't want to add 1000 features to please every client in the world. But I added all the methods and callbacks needed to simply customize and control it.
:)

So, no built-in next/prev buttons, no built-in bullet nav, no built-in thumbnails, etc... Every websites using Vegas would be the same.

Thanks :)
