### ISSUE TITLE
[REQUEST/QUESTION] Slide changed event

### ISSUE THREAD

**Issue by soee** [jaysalvat/vegas#122]
Hi again,

is there any way to execute some code when slide has changed? If not than is it possible to add some event maybe to inform about such action?

**Comment by jaysalvat** [comment]
Hello,

Yes, it's in the documentation with code example.
http://vegas.jaysalvat.com/documentation/settings/#callbacks-events

The Vegas demo uses callbacks too.
http://vegas.jaysalvat.com/demo/

**Comment by soee** [comment]
Ah thank you. I was sure they should be in Methods section and was looging there :(
