### ISSUE TITLE
Images lagging

### ISSUE THREAD

**Issue by jrean** [jaysalvat/vegas#123]
Hi,

Thank you so much for this fantastic plugin.

I have two questions:

```
    $(".page-index .Banner").vegas({
        preload: true,
        animation: 'random',
        delay: 7000,
        slides: [
            {
                src: "/imgs/index/xxx-banner-bg-1.jpg",
                valign: '90%'
            },
            {
                src: "/imgs/index/xxx-banner-bg-2.jpg",
                valign: '90%'
            },
            {
                src: "/imgs/xxx/xxx/xxx-banner-bg-2.jpg",
                valign: '85%'
            }
        ],
    });
```

When I run this page the following things happen:
- I see my dark background then
- The first image loads and is lagging for a very short time
- The second image loads perfectly
- ...

When I check your demo at http://vegas.jaysalvat.com/demo/ the first image loads perfectly and smoothly. I checked your `.js` file and I reckon I'm properly implementing.

Am I missing something?

Last but not least, is it possible to call "globally` vegas to define some global settings that will be applied over each element?

Thank you

**Comment by jrean** [comment]
I found that starting the first image with `animation: 'kenburns',` solves my lagging issue and way way more smoothers.

```
$(".page-index .Banner").vegas({
        preload: true,
        animation: 'random',
        delay: 7000,
        slides: [
            {
                src: "/imgs/index/xxx-banner-bg-1.jpg",
                animation: 'kenburns,
                valign: '90%'
            },
            {
                src: "/imgs/index/xxx-banner-bg-2.jpg",
                valign: '90%'
            },
            {
                src: "/imgs/xxx/xxx/xxx-banner-bg-2.jpg",
                valign: '85%'
            }
        ],
    });
```

If there is an explanation I will be happy to understand.

**Comment by jaysalvat** [comment]
Hello :)

Don't really know why. Sorry.
Is your first image big?

You can apply settings for every slides by setting them directly outside the Slides array.

**Comment by jrean** [comment]
Thanks.
Nope, the images are optimized, compressed, ...
It really solves the issue if I just set an animation for the first image. Weird.

Anyway, it works like a charm.
Thank you
