### ISSUE TITLE
Slideshow isn't displaying images in Firefox

### ISSUE THREAD

**Issue by sppierce** [jaysalvat/vegas#124]
Hi jaysalvat,

First off thank you for such a lightweight, versatile plugin. I've had great experiences so far, though I am currently stumped. 

Presently the slideshow works great in Chrome/IE, though I am unable to get the images to display when testing the website in Firefox. The website in particular is [BaseballForever](http://www.baseballforever.com/). 

Thank you for the help!

**Comment by ginsterbusch** [comment]
Well .. it works fine in Firefox. Though it appears that the navbar is somehow interfering .. 

cu, w0lf.

**Comment by sppierce** [comment]
@ginsterbusch Thank you for the reply. The navbar doesn't seem to affect the slideshow in either of the other major browsers. Also, I removed it completely and the slideshow still fails to display the images. :(

**Comment by ginsterbusch** [comment]
your code suggest you're aiming vegas at div.head .. (for testing purposes, I would not use a minified version; sometimes, minification / optimization might lead to unwanted results = breaking the script).

.. so vegas is triggering the .head class, which is part of the navigation. is that what you want to do? 

cu, w0lf.

**Comment by sppierce** [comment]
@ginsterbusch No luck. I have broken the nav out of the .head div and I am still having no luck. Ideally, I'd like the slideshow to target the same .head div. This is all very odd considering it displays without any problems in the other browsers.

Thanks for spotting that js error, looks to have been an extra space there. Still getting an error for some reason though, will have to look further. 

I appreciate you working with me on this.

**Comment by ginsterbusch** [comment]
Maybe its a missing div? Or the other browsers are ignoring some errors, like an unclosed div (or one that closes at the wrong place). 

BTW: in which browsers did you test it? 

cu, w0lf.

**Comment by ginsterbusch** [comment]
ps: its certainly running, just not visible. Firebug shows me running it just fine.

**Comment by sppierce** [comment]
My initial thought was that it was simply a z-index issue, I wasn't so lucky. Playing around with the img src and absolute links had no effect. This is very puzzling, and frustrating.

**Comment by sppierce** [comment]
A barebones version of this issue example can be found [here](http://www.baseballforever.com/index-test.php). When viewing this link in Chrome/IE all is well, however when you view it in Firefox you no longer get images. The slides respond to background color changes, however the images still fail to display.

**Comment by jaysalvat** [comment]
Hello, did you find a solution ? If so, please share for other users :)

**Comment by sppierce** [comment]
Sorry, no solution was ever found. I unfortunately had to switch to another slideshow plugin.

**Comment by jaysalvat** [comment]
Ok, sorry to hear that :)

Vegas has no known issue with Firefox. My guess is, it's due to a conflict with one of your others plugins.
