### ISSUE TITLE
Animation for specific image

### ISSUE THREAD

**Issue by NilakArgento** [jaysalvat/vegas#126]
How to setup animation for specific image, not for all.
`	$elmt = $("#intro");
		$elmt.vegas({
		    slides: [
		        { src: 'images/bg1.png' },
		        { src: 'images/bg7.png' }
		    ],
		    animationRegister: [ 'firstslide'],
		    animation: [ 'firstslide', 'kenburnsLeft']
		});`

**Comment by jaysalvat** [comment]
Hello,
You can set it in the slide array, just after/before the src option.
