### ISSUE TITLE
Problem to include vegas on joomla

### ISSUE THREAD

**Issue by maofree** [jaysalvat/vegas#127]
hi
I'm tring to include your plugin into a website made with joomla
but I can't see any background image
all seems ok
I tried to include it on my static website and it worked well
I try to associate it on a div but nothing

$doc->addStyleSheet(JURI::base() . 'modules/mod_maohomegallery/css/vegas.css', 'text/css', 'all');
$doc->addScript(JURI::base(true) . '/modules/mod_maohomegallery/js/vegas.js', 'text/javascript');

$doc->addSCriptDeclaration("
    jQuery('#mainarticle').vegas({
        slides: [
            { src: '".JURI::base()."modules/mod_maohomegallery/images/prova.jpg' },
            { src: '".JURI::base()."modules/mod_maohomegallery/images/prova1.jpg' }
        ]
    });
");

the scripts are loaded correctly

thanks

**Comment by jaysalvat** [comment]
Hello,
I'm not a Joomla expert, but your slide paths must be wrong.

Try something like: 
slides: [
        { src: 'images/

or 
slides: [
        { src: '/images/

**Comment by maofree** [comment]
Hi
I think the problem is not due from the path, because if I set src: '/images/ from firebug I get an error of wrong url, instead if I set  src: 'images/ all seems ok but the images don't appear. I try to change the div but with the same result.

try to have a look
http://maofree.changeip.net/travaglio/osteria-gelateria/
at first login set two times "maofree"

thanks

**Comment by maofree** [comment]
Hi
after some test I've solved that problem, now it works very well
thanks
bye

**Comment by jaysalvat** [comment]
Share for other devs please.

**Comment by maofree** [comment]
ok
in the main file of the module it is necessary to use these instructions
for my site it was necessary also to add a line of css code to that div
height: auto !important;
to avoid a problem with the fixed height set from the plugin to it,
necessary like when I load the page when firebug is open, when I close firebug the height doesn't change, the images cover only a part of that div

`
$doc->addStyleSheet(JURI::base() . 'modules/mod_maohomegallery/css/vegas.min.css', 'text/css', 'all');
$doc->addScript(JURI::base(true) . '/modules/mod_maohomegallery/js/vegas.min.js', 'text/javascript');
$doc->addSCriptDeclaration("
    jQuery(document).ready(function(){
        jQuery('#homegallery-background').vegas({
            delay: 9000,
            preload: true,
            timer: false,
            transition: 'zoomOut',
            transitionDuration: 2000,
            slides: [
                { src: '".JURI::base() . "modules/mod_maohomegallery/images/piazza.jpg' },
                { src: '".JURI::base() . "modules/mod_maohomegallery/images/giardino.jpg' },
                { src: '".JURI::base() . "modules/mod_maohomegallery/images/pasta.jpg' },
                { src: '".JURI::base() . "modules/mod_maohomegallery/images/bruschetta.jpg' },
                { src: '".JURI::base() . "modules/mod_maohomegallery/images/salumi.jpg' }
            ]
        });
    });
");`

bye
