### ISSUE TITLE
Overlay effects

### ISSUE THREAD

**Issue by Lolandez** [jaysalvat/vegas#131]
Is possible to add overlay texts animations to the plugin?
I tried to add them by myself but I get many errors.

My script only works over the slides, but not on each background picture.

**Comment by jaysalvat** [comment]
Hello :)

There is no built-in way to do that.
Vegas is a background slideshow plugin. Foreground is up not in the scope of vegas.
You can easily find thousands of regular slideshow plugin out there.

You can use the `walk` callback to change your text and use your own transition though.

Please use support contact (http://vegas.jaysalvat.com) if you need me to work on some examples.

Thanks :)
