### ISSUE TITLE
Slide prev/next transition issue

### ISSUE THREAD

**Issue by qodeboy** [jaysalvat/vegas#132]
Hello,

Please see your official page here http://vegas.jaysalvat.com/documentation/methods/

If you scroll to the bottom where example is and follow this step, you will see an issue:

1. Click "Run Code"
2. Click a.next to go to the next slide.
3. Click a.previous to go to the previous slide.
4. Click a.next one more time. Notice wrong transition is used. Per code "slideLeft2" should be used, but istead something similar to "slideLeft" is used. So instead of pushing previous slide beyond viewport, new active slide flies above it. This happens only if you navigate back before navigating forward. If you just navigate forward, correct transition is used.

Please let me know if any additional info is needed.

Thanks,
Paul.

**Comment by qodeboy** [comment]
It worth to mention last correctly working release is 2.0.3, so issue got introduced somewhere between 77663a9 and bc0584c.

**Comment by jaysalvat** [comment]
Thanks a lot @qodeboy for this report.

It's a known issue to me. Problem with how CSS transitions work.
Refactoring was a bad idea :)

Thanks for pointing me to those commits.

**Comment by jaysalvat** [comment]
Fixed. V2.3.0 Released.
