### ISSUE TITLE
I want to update vegas from, 1.3.5 => actual (2.2.1)

### ISSUE THREAD

**Issue by j0rt3g4** [jaysalvat/vegas#133]
I have brought this theme:
https://wrapbootstrap.com/theme/twilli-air-minimalist-one-page-theme-WB0196957

But then I found that it has some issues, and it uses Vegas Background Plugin 1.3.5 - http://vegas.jaysalvat.com/

I want to update it to the actual version 2.2.1
the package is [here](https://www.dropbox.com/s/9m2hfchiih14yyk/twilli_air_1.3.0.rar?dl=0)

**Comment by jaysalvat** [comment]
Hello,

No magic here.

1 - Download Vegas 2
2 - Replace Vegas 1 by Vegas 2
3 - Find Vegas 1 calls in your theme and replace by Vegas 2 calls

It might be a better idea to contact the Theme author if you want him to update his Theme.

Regards.

**Comment by j0rt3g4** [comment]
Thank you, looking it this way is not rocket science, but do you have any documentantion of how were the v1 calls ? because right now I only see the documentation of V2 in page, so I can identify and do the recipe you just commented. (Thank you by the answer btw)

**Comment by jaysalvat** [comment]
You can find V1 documentation here:
http://v1.vegas.jaysalvat.com/

**Comment by j0rt3g4** [comment]
Thank you jay!
