### ISSUE TITLE
walk() callback frequency increased vegas slider

### ISSUE THREAD

**Issue by Anil8753** [jaysalvat/vegas#136]
I am using vegas background slider in my angular js application. I have code like :

```
app.controller('HomeController', function ($scope, $timeout, $http) {

    $http.get('/GetHomeSliders').then(function (response) {

    var files = [];

    response.data.data.forEach(function (file) {
      files.push({ "src": "/data/home_slider/" + file })
    }, this);

    $("#map").vegas({
      slides: files,
      walk: function (index, slideSettings) {
        console.log("Slide index " + index + " image " + slideSettings.src);
      }
    });
  },
    function (error) {
      alert('error');
    });
});
```
Whenever I visit this angular page again and again, "HomeController" get called that many time, leads to  $http.get('/GetHomeSliders') call. I feel vegas div reinitialized. every slide change works fine but "walk()' callback frequency get increased exponentially.

How can I solve this issue. I need to change the home page messages on this walk() callback.

**Comment by jaysalvat** [comment]
Hello.
You apply Vegas to your element every time the controller is called.
Try to apply it just once or use the destroy method in Vegas.

Regards.

**Comment by Anil8753** [comment]
I did not find any destroy method in $vegas

**Comment by jaysalvat** [comment]
Here:
https://github.com/jaysalvat/vegas/blob/master/dist/vegas.js#L685-L702

Documentation
http://vegas.jaysalvat.com/documentation/methods/
