### ISSUE TITLE
First slide showing for a second sometimes

### ISSUE THREAD

**Issue by angelcj** [jaysalvat/vegas#137]
These are my settings: 

  $("body.page-template-ourwork-page").vegas({
    preload: true,
    timer: false,
    transitionDuration: 5000,
    slides: slides,
    transition: ['zoomOut2']
    });

I'm generating the slides externally as I'm using WordPress. Anyway, the all load nicely, but when third slide comes in, for almost a second the first one appears between the second and the third, and it happens sometimes with the fourth as well (there are seven in total). Is that a known issue? I don't know why the first one is shown after it has disappeared.

Thanks.

**Comment by jaysalvat** [comment]
Hello,
It's not a known issue. 
I can't reproduce it on my tests. Sorry.
