### ISSUE TITLE
background-attachment fixed

### ISSUE THREAD

**Issue by devdurbs** [jaysalvat/vegas#138]
Hi Jay

Thank you for an outstanding script!

Any idea how I can get the slide container to be fixed? The background-attachment: fixed seems to be ignored.

Tks
Ray

**Comment by devdurbs** [comment]
Anything ?

**Comment by jaysalvat** [comment]
Hello.

It seems fixed backgrounds don't work with background-size cover/contain.
We can't do much.
Tell me if you find something.

Thanks.
