### ISSUE TITLE
bad performance -  CPU GPU and memory

### ISSUE THREAD

**Issue by jmbelloteau** [jaysalvat/vegas#139]
Hello guys,

Jay, first of all, a big up for your amazing Vegas plugin ! 💯 
I'm using it on my website and I'm very happy with it : https://www.jmbelloteau.com

I'm just having some pretty bad performances issues. It's look like Vegas use a **LOT** of CPU GPU and memory for no reason. (a 4K youtube video run better on the same computer) 🙃 

Am I the only one having this problem? Any way to improve this?

Thank you guys

Cheers

Jim

**Comment by jmbelloteau** [comment]
bump !!

Any idea to optimize the performance ?

**Comment by jmbelloteau** [comment]
Hello @jaysalvat,

Do you have any idea about this problem?

Thank you

**Comment by jaysalvat** [comment]
Hello,
Your pictures are 3000x2000.
Your slideshow contains 46 slides.
Some pictures are +1mb (https://www.jmbelloteau.com//app/medias/home/slideshow/5.jpg)

Your optimisation should start there :)

**Comment by jmbelloteau** [comment]
Hello @jaysalvat !

As I had same performance problem on your demo site, I though maybe something could be optimise somwhere :)

But of course my pictures don't help... :)

Thanks for your answer anyway

**Comment by jaysalvat** [comment]
It certainly can be optimized. It's an open-source project. Help is welcomed.
