### ISSUE TITLE
Transition errors when applying Vegas to a div

### ISSUE THREAD

**Issue by meta4creations** [jaysalvat/vegas#140]
When I add Vegas to a DIV, as opposed the the body, the previous images do not get removed from the screen right away. This can be seen clearly when using "cover: false" and different sized images as you can see older, larger images stacked up behind the current image.

This does not happen when applying the exact same settings to the body.

**Comment by jaysalvat** [comment]
Hello,
We need to keep some slides in the background for some transition.
I didn't see anything really noticable.
Can you provide an example ?

Did you try forcing the slide background color?

    { color: 'black' }

**Comment by meta4creations** [comment]
Thanks!

`{ color: 'black' }`

Resolved my issue.
