### ISSUE TITLE
Autoplay video on mobile

### ISSUE THREAD

**Issue by logiclabs** [jaysalvat/vegas#141]
As of Safari on iOS 10, Chrome for Android v53 and Firefox on Android, background videos can now autoplay on mobile, if they are muted or have no audio tracks.  

The current code in Vegas prevents video running on all mobiles by user agent. 

I have created a bit of a hack to get this working for my own site. With a bit more testing, I may be able to submit a PR.

[iOS Video Policy changes](https://webkit.org/blog/6784/new-video-policies-for-ios/)
[Chrome Android Video Policy changes](https://developers.google.com/web/updates/2016/07/autoplay)

**Comment by jaysalvat** [comment]
Hello and thanks for your feedback.

You are right, by default Vegas prevents video running on all mobile devices by user agent.
But as mentioned in the documentation (bottom of the page) you can set your own rule by overwriting the method. http://vegas.jaysalvat.com/documentation/settings/

    $.vegas.isVideoCompatible = function () {
        return true;
    }

I have no time to work on new device OS video autoplay, so thanks a lot for your future PR :)
I will check that carefully.
