### ISSUE TITLE
Refresh after content size change without re-building the slideshow.

### ISSUE THREAD

**Issue by whitehollow** [jaysalvat/vegas#142]
Hi, it is possible to add a refresh/reload method to update the slideshow if the content height/width has changed. Right now if the size change the slideshow remains with the same dimensions and leaves blank spaces which looks bad, the only way is to destroy the slideshow and recreate it.

Thank you

**Comment by jocon128** [comment]
Did you manage to fix this?
I would like to do the same.
Thanks Jamie
