### ISSUE TITLE
Bandwidth Hog with Videos 

### ISSUE THREAD

**Issue by abidCharlotte49er** [jaysalvat/vegas#145]
Hi Jay, 

Hope you are doing well. We have noticed a peculiar bug related to Video being downloaded multiple time and hence causing Bandwidth Hog. Please see the  image below, we are using one slide which is about 5.3 MB and over the time the browser loads this content over and over. You can see the same 5.3 MB video is pulled from the server over and over. Is there a reason why the content is being loaded multiple time? I tried using preload option it didn't help either. Thanks 

Here is the sample video http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 

![image](https://cloud.githubusercontent.com/assets/2357276/23371020/a6456ce2-fce4-11e6-8af0-b31e7a243b64.png)

**Comment by danieldiazastudillo** [comment]
The first src is for a fallback image, not a video (check that first)

**Comment by abidCharlotte49er** [comment]
There was a bug in Chrome related to caching. This should be fixed with their updates.
