### ISSUE TITLE
Display a caption or the tag "title" or "alt" of each background

### ISSUE THREAD

**Issue by Dannn04** [jaysalvat/vegas#146]
Hello

I would like to display a caption or the tag "title" or "alt" of each background
Is there a way ?
How do I proceed to do this (code) ?

thanks a lot for your help
Dan

**Comment by jaysalvat** [comment]
Hello,
Use the 'walk' callback or event to change your texts when slides change.
http://vegas.jaysalvat.com/documentation/methods/
