### ISSUE TITLE
Controll the zooming out.

### ISSUE THREAD

**Issue by ultrasamad** [jaysalvat/vegas#147]
How can I control the zooming out of the image before it is replaced by the next one. When the image appears, it is kind of cropped and as it fades out, it nearly displayed it **full content**, but not all of it is shown before the **next image appears**. I want that in the process of fading out, it should display all of it before disappearing.

**Comment by jaysalvat** [comment]
Adjust the transition in the css file.

Some doc here.
http://vegas.jaysalvat.com/documentation/transitions/
