### ISSUE TITLE
SHOW VARIOUS DIVS WITH SLIDE

### ISSUE THREAD

**Issue by ugrcn** [jaysalvat/vegas#148]
Hey there, 

how can I show various divs while it runs? I have to write something about pictures which are items of vegas-slider.

**Comment by Dannn04** [comment]
I want this code too
Thanks

**Comment by MarFan** [comment]
It might not be the best way, but here is what I have done to show a different divs depending on the slide:

Start out with all #wow .slide*-content `display: none;`

`$('#wow').vegas({  // #wow is the container`
 ` timer: false,`
  `slides: [`
    `{src: '/assets/images/slides/slide-bg3.jpg', container: '.slide1-content'}, //slides are children of #wow`
    `{src: '/assets/images/slides/location.jpg', container: '.slide2-content'},`
    `{src: '/assets/images/slides/slide-bg6.jpg', container: '.service-slide'}`
`],`
  `overlay: '/site-assets/vegas-2.4.0/overlays/06.png',`
 ` walk: function(index, slideSettings){`
  `  $('#wow .slide').not(slideSettings.container).hide(); // hides slides`
    `$('#wow '+slideSettings.container).fadeIn('slow'); // fades in the desired slide`
`	}`
`});`

Hopefully this might help.

**Comment by Dannn04** [comment]
Hello

I tried to put this code on my gallery but I lack experience and knowledge and I can not seem to make it work

Would it be possible to see the whole code or an example online?

Thank you

**Comment by MarFan** [comment]
Try this: https://jsfiddle.net/kdjccwxw/3/

**Comment by Dannn04** [comment]
Thanks, 
now it's ok !
(It was necessary to use jquery and not zepto)

Many thanks

**Comment by unforgivenJ** [comment]
@MarFan I tried the fiddle, it is working, but how to change the fadeIn duration of a heading, I tried to set it to 'slow' or '2500' , but still in every slide heading fades in without duration. Thanks!
