### ISSUE TITLE
Microsoft IE11 Animation is Shaky

### ISSUE THREAD

**Issue by simmonsr** [jaysalvat/vegas#151]
We just implemented a new slideshow in our latest RocketTheme template and we've found that the animation being used on each slide in IE11 is literally 'shaky'. We can see the issue on your demo too:

http://vegas.jaysalvat.com/

**Comment by jmichaelterenin** [comment]
Specifically, I'm seeing a flash/flicker when utilizing the SlideRight2/SlideLeft2 in MS Edge. It's noticeable in your demo as well (last one): http://vegas.jaysalvat.com/documentation/methods/

**Comment by DamirPecnik** [comment]
Is this plugin still in active development? This is still an issue?

**Comment by jaysalvat** [comment]
Hello,

Vegas is still active.

I don’t know if IE dev have fixed this issue.

__

Jay Salvat
http://www.jaysalvat.com

**Comment by leviwheatcroft** [comment]
This is still present in v2.4.4 & ie11 when using 'kenburns' animation.
