### ISSUE TITLE
Slideshow working in Dreamweaver CC preview but not in Chrome

### ISSUE THREAD

**Issue by Uri92** [jaysalvat/vegas#152]
Hi,

The slideshow is working fine in the Dreamweaver CC preview, but only a white background is shown in Google Chrome/Safari/Opera. A minimal example of the code which works in Dreamweaver but does not in Chrome:

```HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Homepage</title>


<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="/js/vegas/vegas.min.css">
<script type="text/javascript" src="/js/vegas/vegas.min.js"></script>
	

<script>
$( function() {
    $("body").vegas({
    slides: [
      { src:'images/Image1.jpg', fade:1000 },
      { src:'images/Image2.jpg', fade:1000 },
      { src:'images/Image3.jpg', fade:1000 }
        ]
    } )( 'overlay' );
        });
</script>
  

</head>
<style>
</style>

<body>
</body>
</html>
```

**Comment by Dannn04** [comment]
Like this  ? 

`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Homepage</title>

<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="/js/vegas/vegas.min.css">
<script type="text/javascript" src="/js/vegas/vegas.min.js"></script>
</head>

<body>

<script>
$( function() {
    $("body").vegas({
    slides: [
      { src:'images/Image1.jpg', fade:1000 },
      { src:'images/Image2.jpg', fade:1000 },
      { src:'images/Image3.jpg', fade:1000 }
        ]
    } )( 'overlay' );
        });
</script>

</body>
</html>`
