### ISSUE TITLE
Vegas Slideshow Only Displays 2 of 8 Total Images

### ISSUE THREAD

**Issue by ryancito02** [jaysalvat/vegas#156]
I have a website, so-and-so.com, and I currently use Vegas to handle a full-background slideshow.
I have the following code in my HTML file, which worked when I only had two images in the slides,
However, yesterday, I got 6 more images to add to the slideshow, and so I added them in slides:
and expected it to work right off the bat,

It didn't. Here is my HTML code:

	 <div class="overlay vegas-container" style="height: 974px;">
                 <div class="vegas-slide vegas-transition-fade vegas-transition-fade-in" style="transition: all 5000ms;">
                     <div class="vegas-slide-inner vegas-animation-kenburns" style="background-color: rgba(0, 0, 0, 0); background-position: center center; background-size: cover; animation-duration: 5000ms;"></div></div>
                 <div class="vegas-wrapper" style="overflow: hidden; padding: 0px;">
                 <div class="overlay-dash"></div></div></div> 

And here is the JS file I use:

https://pastebin.com/ceZ3tEvN

I am grateful if you can help me solve this!

**Comment by jaysalvat** [comment]
Don't know without a running example. Sorry.
