### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by CHEMAX3X** [jaysalvat/vegas#166]
Hello, im using your plugin but i have a problem, i call my images from the database and pass them to the plugin but it doesnt read them, however if i copy what is inside the array of images into the plugin it works. Here is my code : 

JS
$.get('ajax/slides.php', function(data) {
    $('#slideMain').vegas({
        slides: [ data ]
    });
 });
////////////////////////////////////////////
AJAX file 
$slide = new slideManager();
$slide ->showSlideController();

echo $slide;
//////////////////////////////////////////
PHP 
public function showSlideController(){
        $answer = slideModel::showSlideModel("slides");
        foreach($answer as $row => $item){
            echo '{ src: "'.$item['path'].'" },'; // Even if i print it like this doesnt work
        }
    }
//////////////////////////////////////// 
Again i got all my images but they are not displayed in the plugin,

Any help will be more than welcome, thanks in advance =D

**Comment by jaysalvat** [comment]
Hello.
You are not generating standard JSON.

1/ PHP must generate a standard JSON array with src inside
2/ JS must load JSON and add it to Vegas properly

Hope it helps.

**Comment by CHEMAX3X** [comment]
Hello, thanks for the reply, look, the problem is that i dont know how to add them to Vegas properly, i have my JSON array and i got the images, for example, if i do this : 

$('#slideMain').append('<img src="'+slides["path"]+'">');

i see all the images, however if i do the same in Vegas, it only displays the first image, and if i left it like:
 
{src: slides}, it only shows me an string with console.log.

Here is the code if it helps : 

foreach($answeras $row => $item){
           $slides[] = array('path'=>substr($item["path"], 6));
        }
        $jsonSlides = json_encode($slides);
        echo $jsonSlides;

And in JS 

$.getJSON('ajax/Slides.php', function(slide) {
    $.each(slide, function(i,newslides){
        $('#slideMain').vegas({
            slides: [
                {src: newslides["path"]}
            ]
        });
    })
});


Thanks again for all your help =D

**Comment by jaysalvat** [comment]
Your keys and json structure seems wrong.
why 'path' ?

**Comment by CHEMAX3X** [comment]
Cuz is the only column that i need from the gallery table, in that table i
have 3 columns: id,path,order, so i dont need id nor order.

When i do a console.log i got this:

[image: Imagen integrada 1]

2018-01-26 10:32 GMT+01:00 Jay Salvat <notifications@github.com>:

**Comment by jaysalvat** [comment]
Give Vegas the JSON it needs and it will work :)
It seems your JSON is not correct.

**Comment by CHEMAX3X** [comment]
Ok, i will see what can i do, thanks again for all your help =)

Best regards =D
