### ISSUE TITLE
How to use images from the internet?

### ISSUE THREAD

**Issue by jackrsantana** [jaysalvat/vegas#168]
Is it possible to use rather than local images, images online from the internet?

Grateful!

**Comment by Wralui** [comment]
Up, I want to know too, I got an API which makes random image by url, is this possible to use it with vegas ?
`https://wallhaven.now.sh/random?keyword=cars`

**Comment by jaysalvat** [comment]
Hello. Yes it's possible.

**Comment by jackrsantana** [comment]
How?

**Comment by jaysalvat** [comment]
Set the picture url instead of the path is the src slide property.

    slides: [
            { src: 'http://www...img1.jpg' },
            { src: 'http://www...img2.jpg' },
            { src: 'http://www...img3.jpg' }
        ]

**Comment by nelsondcosta23** [comment]
Hi Jay,

Can I put php code inside those ' ' where https should go?
Trying to do a dynamic slide show

Thanks

**Comment by Wralui** [comment]
Hi, I tried to put the link 
```
slides: [
        { src: 'https://wallhaven.now.sh/random?keyword=cars' },
    ]
```
But it doesnt request another image, do I need to extract images and send it to vegas first or something like that ? otherwise how ? thanks.

**Comment by ginsterbusch** [comment]
@nelsondcosta23 not wanting to rain into your parade, but this is an issue tracker, not a generic "how to learn basic programming" message board. Thus I'd strongly suggest you [head over to Stack Exchange](https://stackoverflow.com/questions/ask/advice?), where questions like this (AND answers!) are probably more appropriate.



cu, w0lf.

**Comment by nelsondcosta23** [comment]
@ginsterbusch, glad I didnt ask you noyhing. Thanks and keep up into your own business.

@Wralui That link **might** dont work you need to give a img format like .jpg, .png, etc...
If didnt work, your dont you upload the file and copy paste the url?
