### ISSUE TITLE
Strange Glitch with Blur transition

### ISSUE THREAD

**Issue by ldbglobe** [jaysalvat/vegas#174]
Reproductible : http://vegas.jaysalvat.com/documentation/transitions/

Just select Blur transition effect

A screen capture of the glitch is visible here https://youtu.be/Csxgt48pZ1Y

**Comment by jaysalvat** [comment]
Hello and thanks for the PR.
Sorry for the late answer.

I don't have this problem on Chrome Version 67.0.3396.79 (Mac).
So I can't properly test it.

I will merge it asap anyway.

Thanks again.
