### ISSUE TITLE
Blur transition blinks in Chrome

### ISSUE THREAD

**Issue by Blizard** [jaysalvat/vegas#176]
Hi,

i think there is some problem in Blur transition in Chrome. You can see blink after duration time is done and next picture should be shown. Blink is between current picture/slide and next picture/slide.

**Comment by jaysalvat** [comment]
Hello,

Please try this PR and tell me if it's fixed.
https://github.com/jaysalvat/vegas/pull/175

I had no time to check and merge it.

**Comment by jaysalvat** [comment]
PR merged.
