### ISSUE TITLE
Optimize images for faster loading

### ISSUE THREAD

**Issue by batata004** [jaysalvat/vegas#179]
When using VEGAS on a webpage Google PageSpeed report some of the images used by Vegas are not optimized. I would recomment the dev to use https://tinypng.com/ to optimize all the images used by this library (it is a lossless compression and will be marked as 100% optimized by Google pagespeed).

Check image attached of an example of this warning given by Google.

![image](https://user-images.githubusercontent.com/8988923/45067596-4db59c80-b09a-11e8-8e48-62053abf6579.png)

**Comment by batata004** [comment]
Any idea developer? If you with I can compress the image and send you in order to you to send to the CDNs.

**Comment by jaysalvat** [comment]
Thanks for feedbacks. 
Done. Will publish soon.
