### ISSUE TITLE
Incorrect padding in Firefox

### ISSUE THREAD

**Issue by qzminski** [jaysalvat/vegas#200]
We have an issue with padding calculation on Firefox. The script first resets the padding and then it tries to read its values:

https://github.com/jaysalvat/vegas/blob/master/src/vegas.js#L140-L149

This is likely incorrect and the `this.$elmt.css('padding', 0);` padding reset should be moved to line 150 **after the padding values are read**. Otherwise Firefox will never apply the and correct padding.

/cc @milbau

**Comment by jaysalvat** [comment]
Thanks! Should be fixed.
