### ISSUE TITLE
:: THE AUDIO OF THE VIDEOS DOES NOT SOUND ::

### ISSUE THREAD

**Issue by DMVEGA** [jaysalvat/vegas#202]
Good morning .. I am using the video upload everything works very well but the videos are played without sound .. what must be done so that they sound when they are played.

**Comment by jaysalvat** [comment]
Hello. 
I don't really understand what do you mean by "I am using the video upload".
Are you using a wordpress plugin or something like that ? 
I'm the author of Vegas only.

However, Video in background must have sound muted to work properly in background.
