### ISSUE TITLE
Single image: white gap at bottom in Safari iOS 

### ISSUE THREAD

**Issue by jay-b** [jaysalvat/vegas#34]
I have an issue when using a single Vegas background: when you scroll, a white gap appears at the bottom.The problem only occurs in portrait view and doesn't occur when testing with Adobe Inspect (which uses UIWebView). You can replicate the issue by using a single image:
```
  $.vegas({
    src:'img/bkg.jpg'
  });
```
...and by adding an element with enough content to cause scrolling of the page.

Screenshot: https://dl.dropboxusercontent.com/u/5837624/VegasWhiteGapBug.jpg
 
Anyone know a workaround?

**Comment by pateljatin** [comment]
Hi,

I'm seeing this issue now on Firefox 35.0.1 Desktop browser (more apparent on Windows than Mac) - quite frequently. I've also set fade to 0 and it's more visible.

Thanks,
JP

**Comment by pateljatin** [comment]
Update:
somehow it gets fixed if I remove the fade option and set the overlay. if I do not set the overlay, then it is quite visible. I also then added fade at 1000 rate and it does work but still you can see the issue on some pictures initially - however when overlay kicks in immediately, it fixes it.
Just thought I should update you on it...
So I set the overlay to 2.png and fade at 1000.

Thanks,
JP

**Comment by jaysalvat** [comment]
Thanks for the info.
