### ISSUE TITLE
Random Slideshow

### ISSUE THREAD

**Issue by alitabatabaei** [jaysalvat/vegas#38]
Hi guys. Thanks for a great jQuery plugin. works like a charm.
Ok, I'm pretty new to jquery and I wanted to know if there's anyway to make this slideshow show the images randomly and not one after the other?

**Comment by keisersuze** [comment]
Hi every body,

I tried integrate the "randombgs function" (script bellow). It work but my buttons doesn't work. When i click it, it is a bad image (random).

Can you fix it my script please?

Thank you very much!

source: http://vegas.jaysalvat.com/demo/

<code>
$(function() {
	
    var slideshowRunning = false,
        backgroundList = [];

    // Build the background list with href of links
    $('#vegas a').each(function() {
        backgroundList.push({
            src: $(this).attr('href'),
            //valign: $(this).data('valign'),
			//align: $(this).data('align'),
            fade: 2000,
        });
    });
	
	// Define the shuffle function
	function shuffle(o) { //v1.0
		for (var j, x, i = o.length; i; j = Math.floor(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
		return o;
	};
		
	randombgs = shuffle(backgroundList);
	
	// Pass shuffled array to Vegas
	$.vegas('slideshow',  {
		delay: 5000,
		backgrounds: randombgs
	})

    // A short demo
    $('#vegas a').click(function() {

        // If the SlideShow link is clicked
        if ($(this).is('#slideshow')) {

            // Start the SlideShow
            if (slideshowRunning == false) {
                slideshowRunning = true;

                $('#pause')
                    .show()
                    .css('opacity', 0.5)
                    .html('PAUSE');

                $.vegas('slideshow', {
                    delay: 5000,
                    backgrounds: randombgs
                })

                // Pause the SlideShow
            } else {
                slideshowRunning = false;

                $('#pause')
                    .show()
                    .css('opacity', 0.5)
                    .html('PLAY');

                $.vegas('pause');
            }

            // If a standard Thumbnail is clicked
        } else {
            slideshowRunning = false;

            $('#pause').hide();
            $('#thumbnail').attr('src', '../img/slideshow.gif');

            var idx = $(this).parent('li').index();
            $.vegas('stop')(backgroundList[idx]);
        }

        return false;
    });

    // Apply a border to the right thumbnail when a background is loaded
    $('body').bind('vegasload', function(e, bg) {
        var src = $(bg).attr('src').replace('background', 'thumbnail');

        $('#vegas img')
			.removeClass('active');
            //.css('border', '1px solid #FFF');
        $('img[data-src="' + src + '"]')
			.addClass('active');
            //.css('border', '1px solid #CF0');
    });

    // Display the right thumbnail instead of the slideshow animated gif when the slideshow is running
    $('body').bind('vegaswalk', function(e, bg) {
        var src = $(bg).attr('data-src').replace('background', 'thumbnail');
		
        $('#thumbnail').attr('src', src);
    });
});
</code>

**Comment by AlvSovereign** [comment]
For the randomise solution @alitabatabaei put in, please change 'backgrounds' to 'slides' as I think the newer version now uses 'slides' in the options.

Mine looks like this:

// VEGAS Slide Show
		// The Shuffle Function
		function shuffle(o){ //v1.0
		for(var j, x, i = o.length; i; j = Math.floor(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
		return o;
		};

		// Define backgrounds array
		var bgimages = [
		{ src: "/assets/img/slide/slide01.jpg" },
		{ src: "/assets/img/slide/slide02.jpg" },
		{ src: "/assets/img/slide/slide03.jpg" },
		{ src: "/assets/img/slide/slide04.jpg" },
		{ src: "/assets/img/slide/slide05.jpg" },
		{ src: "/assets/img/slide/slide06.jpg" },
		{ src: "/assets/img/slide/slide07.jpg" },
		{ src: "/assets/img/slide/slide08.jpg" },
		{ src: "/assets/img/slide/slide09.jpg" },
		{ src: "/assets/img/slide/slide10.jpg" },
		{ src: "/assets/img/slide/slide11.jpg" },
		{ src: "/assets/img/slide/slide12.jpg" },
		{ src: "/assets/img/slide/slide13.jpg" },
		{ src: "/assets/img/slide/slide14.jpg" },
		{ src: "/assets/img/slide/slide15.jpg" },
		{ src: "/assets/img/slide/slide16.jpg" },
		{ src: "/assets/img/slide/slide17.jpg" },
		{ src: "/assets/img/slide/slide18.jpg" },
		{ src: "/assets/img/slide/slide19.jpg" },
		{ src: "/assets/img/slide/slide20.jpg" },
		{ src: "/assets/img/slide/slide21.jpg" },
		{ src: "/assets/img/slide/slide22.jpg" },
		{ src: "/assets/img/slide/slide23.jpg" },
		{ src: "/assets/img/slide/slide24.jpg" },
		{ src: "/assets/img/slide/slide25.jpg" },
		{ src: "/assets/img/slide/slide26.jpg" },
		{ src: "/assets/img/slide/slide27.jpg" }
		]

		// Suffle the array
		randombgs = shuffle(bgimages);

		$("body").vegas({
			delay: 10000,
			transitionDuration: 3500,
			cover: true,
			slides: randombgs
	});
