### ISSUE TITLE
Loading images from database

### ISSUE THREAD

**Issue by CIRCLE73** [jaysalvat/vegas#50]
I´m using the plugin Jquery Vegas Slideshow in a project and I'm trying to load images directly from my database into the slideshow script.

I have it running with the following code:

```
<script type="text/javascript">
    jQuery.vegas('slideshow', {
        backgrounds:[
            { src:'images/slider/slider_01.jpg', fade:2500 },
            { src:'images/slider/slider_01.jpg', fade:2500 },
        ]
        })('overlay', {
        src:'images/slider/overlays/06.png'
    });
</script>
```

How can I populate the background parameter using Ajax?
I've read the documentation but there is no information about any server side language.

**Comment by shadrackkip** [comment]
I am getting an error Uncaught TypeError: jQuery.vegas is not a function. Where could be the problem
