### ISSUE TITLE
How to add Next/Previous buttons on slideshow?

### ISSUE THREAD

**Issue by hammdy** [jaysalvat/vegas#59]
Hello Jaysalvat,
First of all I must say, you've done a great job with the slideshow. I love it.

Could you please let me know how to add Next/Previous buttons on slideshow? so that we can click and change the slides?

Thanks and much appreciated!

**Comment by gadhafi** [comment]
<script src="js/jquery.min.js"></script>
<script src="js/vegas/vegas.min.js"></script>
<script>

$("#example").vegas({
    slides: [
        { src: 'images/banner/banner-01.jpg' },
		        { src: 'images/banner/banner-03.jpg' },
				        { src: 'images/banner/banner-01.jpg' },
        { src: 'images/banner/banner-02.jpg' }
    ],
    transition: 'slideLeft',
	
});

$('a.next').on('click', function(e) {
    $.vegas('next');
    e.preventDefault();
});
</script>



I have tried this but no hope... its not working... please help
