### ISSUE TITLE
jQuery Vegas as a bower_component does not work well (jquery.vegas.css is not copied in dist)

### ISSUE THREAD

**Issue by Maximebpro** [jaysalvat/vegas#65]
When you bower install vegas in a yeoman / angular project, the grunt dist won't copy the jquery.vegas.css. 

As mentioned here http://stackoverflow.com/a/25716408/689429, wiredep looks at the bower.json configurations of each of your dependencies in bower_components and adds hrefs to app/index based on the main property.

In jaysalvat/vegas's bower.json, you'll find only:
  "main": "dist/jquery.vegas.js",
instead of:
      "main": [
        "dist/jquery.vegas.js",
        "dist/jquery.vegas.css"
      ]

As a workaround, you can override this in your own bower.json using bower overrides as specified here: https://github.com/taptapship/wiredep#bower-overrides

  "overrides": {
    "vegas": {
      "main": [
        "dist/jquery.vegas.js",
        "dist/jquery.vegas.css"
      ]
    }
  },

**Comment by magigedaniel** [comment]
sasas
