### ISSUE TITLE
video loop

### ISSUE THREAD

**Issue by alsemany** [jaysalvat/vegas#71]
Hello,
first I would like to thank you for this great plugin, 
my question is how can I make a background video with loop playing

**Comment by jaysalvat** [comment]
Hello, 

Video were supposed to loop.
Must have remove the option by mistake.
I will work on it.
Thanks.

**Comment by alsemany** [comment]
thank you for your speed reply 
I resolved with this 
$video = $(video)
			.addClass('vegas-video')
			.css('background-color', color)
			.attr("loop", "true");

but still have an issue, the video is on the top, I tried to change the z-index with my css file it still not showing the text. would you please  know why this happened do you have any idea 

Thank you so much

**Comment by jaysalvat** [comment]
Was it happening before your "loop" change?
Is it happening of the demo? http://vegas.jaysalvat.com/demo

If yes, what is your browser?

And remember what the documentation says:
"Experimental video support is provided AS A BONUS. Video backgrounds could not behave as expected on some browsers. Use it at your own risk"
http://vegas.jaysalvat.com/documentation/settings/

;)

**Comment by jaysalvat** [comment]
Just added the video.loop and video.mute options.

No answer on video z-index. I close the issue. Thanks.
