### ISSUE TITLE
no destroy method in vegas 2.0.x?

### ISSUE THREAD

**Issue by sumomostudio** [jaysalvat/vegas#72]
no 'destroy' method in vegas 2.0.x?
did not find it in source code
I used it in 1.3.x, really convinient if it is available.

**Comment by jaysalvat** [comment]
Hello,
There is no destroy method yet.
Will work on it in a near future :)

Thanks.

**Comment by sumomostudio** [comment]
Thank you in advance!
since I am using it as an Angular directive, when 'page'(actually it is an ui-view) is switched to others, I need this destroy method to 'remove' vegas, and that makes sense as it is a new 'page'. :)

**Comment by jaysalvat** [comment]
Just released Vegas 2.1.0 with:

    $elmt.vegas('destroy');

Enjoy.

**Comment by davidutzus** [comment]
cornel@cronoxy.com
Pe 02.04.2015 15:01, "Jay Salvat" <notifications@github.com> a scris:

**Comment by sumomostudio** [comment]
Thanks, I tried the latest one, it works great!
except one little thing...
when I use 
```javasctipt
overlay:true
```
then when I destroy, the overlay only will not be 'destroyed'.
I checked the source code and added 
```javascript
this.$overlay.remove();
```
in destroy function, then the problem seems fixed.
I am still not familiar with how to initiate a pull request, so please give it a look, when you have time.
By the way, transition and animation looks great! Thanks again! Have a nice day! :+1:

**Comment by sumomostudio** [comment]
I just tried a pull request, not sure it is correct or not, please confirm. :-)

**Comment by jaysalvat** [comment]
Thanks you!
But there is a problem with your version.
All the files have change and it includes jquery and all bower_components.

It's impossible for me to merge.

Thanks for your contribution, don't worry. I will add the fix soon anyway. :)

**Comment by JustinLien** [comment]
@jaysalvat could you add this to your documentation? I did not find it so I had to look through your issue to find it here. Thanks!

**Comment by jaysalvat** [comment]
Hello @JustinLien 

It's already there. 
http://vegas.jaysalvat.com/documentation/methods/

Cmd + F -> destroy

:)
