### ISSUE TITLE
Add images to slides list while running

### ISSUE THREAD

**Issue by lardissone** [jaysalvat/vegas#73]
A good feature would be a method to add images to the list of slides.

Example usage: set a websocket sending new uploaded images info to Vegas and automatically display it without refreshing the page(or restart vegas).

**Comment by jaysalvat** [comment]
Hello Lardissone!

Use ```options``` method

Take a look to the last example:
http://vegas.jaysalvat.com/documentation/methods/

Thanks.

**Comment by lardissone** [comment]
Awesome!
Thank you!
