### ISSUE TITLE
No image show at begining with transition slideLeft2

### ISSUE THREAD

**Issue by jonnydevv** [jaysalvat/vegas#77]
When using slideLeft2 as transition no initial image is set before start transitions.
How can i set initial page?

**Comment by jaysalvat** [comment]
Hello.

Use CSS on your container.

It's not a bug. So I close :)

**Comment by jonnydevv** [comment]
The problem using CSS background is:

CSS background image doesn't slide when first slide comes.

**Comment by jaysalvat** [comment]
Ok. Right!

Workaround:
Try to set transition: false to the first slide.
Then set it to the right transition when the second slide is displayed.
