### ISSUE TITLE
jQuery Tabs Conflict

### ISSUE THREAD

**Issue by Stephen0208** [jaysalvat/vegas#80]
If I initialise the slideshow before my tabs then the height of the div is too big as the tabs haven't 'tabbed' yet, if I initialise the slideshow after my tabs my tabs do not work at all. No console errors.

Any ideas why?

**Comment by Stephen0208** [comment]
It's cool, I have changed the slider as it was conflicting with my css as well. Thanks.

**Comment by jaysalvat** [comment]
Great Stephen! 
I can close it now :)
