### ISSUE TITLE
init Vegas using HTML (data-attributes)

### ISSUE THREAD

**Issue by bennyzen** [jaysalvat/vegas#81]
As a possible future enhancement, it would be nice to init vegas using HTML only and maybe data-attributes. This would allow to populate the slides-array from generated markup. Maybe i've overlooked something crucial. So please point me into the right direction.

**Comment by jaysalvat** [comment]
Hello @bennyzen 

Vegas point of view is to add slideshow in the background. Letting foreground elements on top.
Settings slides from foreground elements would be a non-sens with Vegas :)

For a data-attribute, settings so much javascript object information in a simple data tag would be to cumbersome IMHO.

I will think about that and add something like that if I figure out the right way to do it.

Regards.
