### ISSUE TITLE
Slider won't pause immediately

### ISSUE THREAD

**Issue by ewape** [jaysalvat/vegas#82]
I'm trying to pause the slider, but animation keeps going until it's finished, then it stops. 
I tested different settings, switched to transitions, toggled / removed options. It's not browser dependant.
What am I missing?

    $('body').vegas({
          animation: [ 'kenburns', 'kenburnsUp', 'kenburnsDown', 'kenburnsLeft', 'kenburnsRight' ],
          delay: 10000,
          animationDuration: 6000,
          slides: [
          { src: path + 'slider_1.jpg' },
          { src: path + 'slider_2.jpg' },
          ]
        });

    item.click(function(e) {
        e.preventDefault();
        $('body').vegas('pause');
    });

**Comment by jaysalvat** [comment]
Hello,

Pause, pauses the slides, not animations/transitions. 
It is the expected behavior.

Animations and transitions are CSS3 transitions, when they are applied, Javascript can't easily stop them.

**Comment by ewape** [comment]
Could you point me to the solution on how to do that? Not the greatest javascript ninja here

**Comment by jaysalvat** [comment]
I have no solution without testing dozen lines of code.

Google "javascript stop css transition":

For ex. http://stackoverflow.com/questions/12930098/how-to-stop-css3-transition
