### ISSUE TITLE
Question on Mobile Orientation Change

### ISSUE THREAD

**Issue by DaveyJake** [jaysalvat/vegas#84]
Just curious how you were able to achieve such a fluid change when viewing on mobile?  I'm using Vegas on one of my web pages but can't seem to achieve that same fluidity when viewing on a mobile device.

Any advice would be greatly appreciated.  Keep up the great work!

**Comment by jaysalvat** [comment]
Hello!
Nothing special. Just built-in Vegas resizing. 
Do you use Vegas2 ?

**Comment by DaveyJake** [comment]
Yes sir. Version 2.1.3 to be exact.

Open this URL on your smart phone -- http://bit.ly/usavhar -- and when rotating your device you'll see what I mean.  I've compressed all of my images to be under 150KB but I just can't get it to transition as smooth as the Vegas homepage does when viewed on mobile.

**Comment by jaysalvat** [comment]
It's a bit slower than vegas but nothing really noticeable on my iphone6.

You have some orientation fixes and viewport alteration scripts. They might slow down some things I guess. Don't really know :)

**Comment by DaveyJake** [comment]
Adjusted the timer inside of the alteration script.  Problem solved!  Thank you for point that out!

**Comment by jaysalvat** [comment]
Great!
