### ISSUE TITLE
Not showing any images (Not Working)

### ISSUE THREAD

**Issue by webtuts4u** [jaysalvat/vegas#87]
Following all of the guidelines given, and result is blank page. Its to hard to found the mistake. Because non of error given.

Please add a example.

Here the Code:

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="vegas/vegas.js"></script>
	<script>
	$(function() {
		$elem = $('.wrap');
		$elem.vegas({
			preload:true,
	    	 	transitionDuration:4000,
			delay:10000,
			slides: [
				{ src: 'img/1.jpg' },
				{ src: 'img/2.jpg' },
				{ src: 'img/3.jpg' },
				{ src: 'img/4.jpg' },
				{ src: 'img/5.jpg' }
			]
		});
	}	
	</script>

Anybody here to mark the mistake.

**Comment by slavajacobson** [comment]
Having issues too..

I used the code from the github Readme


```coffee
  $('body').vegas slides: [
    { src: '/images/1.jpg' }
    { src: '/images/2.jpg' }
    { src: '/images/3.jpg' }
  ]
```

Nothing's showing up

**Comment by jaysalvat** [comment]
Hello Guys,

It works well for me. Vegas website uses the latest version. This not a Vegas bug.  
Check your code or read the jQuery documentation. Vegas works like every other jQuery plugins.

@webtuts4u
Your code seens right.
There is some examples in the documentation and a demo on http://vegas.jaysalvat.com

@slavajacobson 
This is not the code from the Readme.

**Comment by webtuts4u** [comment]
Thanks @jaysalvat 

Its to hard to get the right markup for js. I found my solution. If its possible for you, please add the small basic demo in the repository.

Thanks again.

:smile:
