### ISSUE TITLE
Pause ignores delay

### ISSUE THREAD

**Issue by errozero** [jaysalvat/vegas#98]
When pausing a slideshow, the delay property of the current slide is not paused.

So if I have a slide with a delay of 10 seconds and pause after 2 seconds, then wait 30 seconds and unpause - it will  immediately jump to the next slide. It should stay on the last slide for another 8 seconds before moving to the next.

**Comment by jaysalvat** [comment]
Hello!

This is the expected result.
Most of the time, when a user pauses a slideshow to look at a picture and then plays it back, he doesn't want/need to have the remaining time again because he had all the time he wanted to looking at the current slide.
Sorry you need something else :)

**Comment by errozero** [comment]
Ok, that makes sense. I think I can work around it in my app.
Cheers.
