### ISSUE TITLE
overlay not displaying

### ISSUE THREAD

**Issue by bravo14** [jaysalvat/vegas#99]
I have specified a URL for an umage for overlay, however the overlay is not displaying.

The code below is what I have displaying

```<script>
$(document).ready(function(){
$('body').vegas({
    slides: [
        { src: "http://www.iowislanders.co/images/saul_bg.jpg" }
    ],
	overlay: 'http://www.iowislanders.co/img/black.png',
	delay: 0,
	transition:'flash'
});
 });
</script>```

The vegas overlay container is popualting with the overlay image, but it is not displaying the image

**Comment by jaysalvat** [comment]
Hello,
It works well for me on Chrome.

**Comment by bravo14** [comment]
Trying in Firefox, IE and Mobile Safari, and not displaying

**Comment by bravo14** [comment]
The URL is http://www.iowislanders.co/riders?riderId=3

**Comment by jaysalvat** [comment]
Hello,
All my tests are ok.

I also see you now used an css background, it's a better practice than using an alpha image.
So I close :)
